
// http://localhost:4200/chm/backend/sites/415/reports/top-five-products
export const MOCK_REPORT_TOP_5_PRODUCTS = [ { "name":"Product A", "productId":1001, "brand":"Marca A", "model":"Modelo A", "alphaCode":"Alfa A", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":500 }, { "channelName":"eBay Portugal", "numSells":123 }, { "channelName":"Modalia", "numSells":80 }, { "channelName":"Amazon", "numSells":23 } ] }, { "name":"Product B", "productId":1002, "brand":"Marca B", "model":"Modelo B", "alphaCode":"Alfa B", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":123 }, { "channelName":"eBay Portugal", "numSells":342 }, { "channelName":"Modalia", "numSells":39 }, { "channelName":"Amazon", "numSells":134 } ] }, { "name":"Product 3", "productId":1002, "brand":"Marca C", "model":"Modelo C", "alphaCode":"Alfa C", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":124 }, { "channelName":"eBay Portugal", "numSells":231 }, { "channelName":"Modalia", "numSells":143 }, { "channelName":"Amazon", "numSells":90 } ] }, { "name":"Product D", "productId":1004, "brand":"Marca D", "model":"Modelo D", "alphaCode":"Alfa D", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":73 }, { "channelName":"eBay Portugal", "numSells":76 }, { "channelName":"Modalia", "numSells":55 }, { "channelName":"Amazon", "numSells":26 } ] }, { "name":"Product E", "productId":1008, "brand":"Marca E", "model":"Modelo E", "alphaCode":"Alfa E", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":61 }, { "channelName":"eBay Portugal", "numSells":103 }, { "channelName":"Modalia", "numSells":28 }, { "channelName":"Amazon", "numSells":93 } ] } ];

// http://localhost:4200/chm/backend/sites/415/reports/top-fifteen
export const MOCK_REPORT_TOP_FIFTEEN = [ { "name":"2ªQ.Julio", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":1500 }, { "channelName":"eBay Portugal", "numSells":1123 }, { "channelName":"Modalia", "numSells":180 }, { "channelName":"Amazon", "numSells":123 } ] }, { "name":"1ªQ.Diciembre", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":1123 }, { "channelName":"eBay Portugal", "numSells":1342 }, { "channelName":"Modalia", "numSells":139 }, { "channelName":"Amazon", "numSells":1134 } ] }, { "name":"2ªQ.Diciembre", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":1124 }, { "channelName":"eBay Portugal", "numSells":1231 }, { "channelName":"Modalia", "numSells":1143 }, { "channelName":"Amazon", "numSells":190 } ] }, { "name":"1ªQ.Enero", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":173 }, { "channelName":"eBay Portugal", "numSells":176 }, { "channelName":"Modalia", "numSells":155 }, { "channelName":"Amazon", "numSells":126 } ] }, { "name":"1ªQ.Septiembre", "sellsPerChannel":[ { "channelName":"eBay España", "numSells":161 }, { "channelName":"eBay Portugal", "numSells":1103 }, { "channelName":"Modalia", "numSells":128 }, { "channelName":"Amazon", "numSells":193 } ] } ];

// http://localhost:4200/chm/backend/sites/415/reports/average-ticket
export const MOCK_REPORT_AVERAGE_TICKET = [ { "channelName":"eBay España", "amount":19.55 }, { "channelName":"eBay Portugal", "amount":17.75 }, { "channelName":"Modalia", "amount":24.10 }, { "channelName":"Amazon", "amount":31.20 } ];

// http://localhost:4200/chm/backend/sites/415/reports/sells-evolution
export const MOCK_REPORT_SELLS_EVOLUTION = [ { "period":"Nov'17", "sells":[ { "channelName":"eBay España", "numSells":1500 }, { "channelName":"eBay Portugal", "numSells":1123 }, { "channelName":"Modalia", "numSells":768 }, { "channelName":"Amazon", "numSells":123 } ] }, { "period":"Dic'17", "sells":[ { "channelName":"eBay España", "numSells":1234 }, { "channelName":"eBay Portugal", "numSells":1342 }, { "channelName":"Modalia", "numSells":804 }, { "channelName":"Amazon", "numSells":1134 } ] }, { "period":"Ene'18", "sells":[ { "channelName":"eBay España", "numSells":1124 }, { "channelName":"eBay Portugal", "numSells":1231 }, { "channelName":"Modalia", "numSells":857 }, { "channelName":"Amazon", "numSells":190 } ] }, { "period":"Feb'18", "sells":[ { "channelName":"eBay España", "numSells":1134 }, { "channelName":"eBay Portugal", "numSells":1222 }, { "channelName":"Modalia", "numSells":900 }, { "channelName":"Amazon", "numSells":126 } ] }, { "period":"Mar'18", "sells":[ { "channelName":"eBay España", "numSells":1367 }, { "channelName":"eBay Portugal", "numSells":1476 }, { "channelName":"Modalia", "numSells":790 }, { "channelName":"Amazon", "numSells":193 } ] } ];
